name: Run Parked Domain Check Script

on:
 #schedule:
 # - cron: '0 2 1 * *'
 workflow_dispatch:

permissions:
 contents: write

jobs:
 run-script:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: 3.11

     - name: Check Parked Status
       run: python tools/check_parked_domains.py

     - name: Commit and Push
       run: |
         git config --global user.email "<>"
         git config --global user.name "GitHub-Actions"
         git add logs
         git commit -m "Update parked domains log"
         git push
