name: Download file
on:
 schedule:
   - cron: '0 0 * * 0'
 workflow_dispatch:

jobs:
 download_file:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout repository
     uses: actions/checkout@v3

   - name: Download file
     run: |
       mkdir -p lists
       wget -P lists https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/lists/main.txt

   - name: Commit and push changes
     uses: stefanzweifel/git-auto-commit-action@v4
     with:
       commit_message: Update lists
       file_pattern: lists/*
