name: Extract domains

on:
 workflow_dispatch:

permissions:
 contents: write

jobs:
 run-script:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up Python
       uses: actions/setup-python@v5
       with:
         python-version: 3.11

     - name: Create Domains File
       run: python tools/extract_domains.py

     - name: Commit and Push
       run: |
         git config --global user.email "<>"
         git config --global user.name "GitHub-Actions"
         git add logs/domains.txt
         git commit -m "Update logs"
         git push
